/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.2.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Friday, October 4, 2019
 ***********************************************************************************************/

#ifndef SENSEHAT_INTERFACE_H
#define SENSEHAT_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"

#include "digitaltwin_client_helper.h"
#include "digitaltwin_serializer.h"
#include "parson.h"
#include "../SenseHatModel_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum SENSEHAT_TELEMETRY_TAG
{
    Sensehat_TEMPERATURE_TELEMETRY,
    Sensehat_HUMIDITY_TELEMETRY,
    Sensehat_PRESSURE_TELEMETRY
} SENSEHAT_TELEMETRY;

// DigitalTwin interface name from service perspective.
static const char SensehatInterfaceId[] = "urn:sense_hat:SenseHat:1";
static const char SensehatInterfaceInstanceName[] = "sensehat";

// Telemetry names for this interface.

static const char SensehatInterface_TemperatureTelemetry[] = "temperature";

static const char SensehatInterface_HumidityTelemetry[] = "humidity";

static const char SensehatInterface_PressureTelemetry[] = "pressure";

// Property names for this interface.

// Command names for this interface

#define SensehatInterface_Show_messageCommand "show_message"

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE SensehatInterface_Create();

void SensehatInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

DIGITALTWIN_CLIENT_RESULT SensehatInterface_Telemetry_SendTemperature();

DIGITALTWIN_CLIENT_RESULT SensehatInterface_Telemetry_SendHumidity();

DIGITALTWIN_CLIENT_RESULT SensehatInterface_Telemetry_SendPressure();

DIGITALTWIN_CLIENT_RESULT SensehatInterface_Telemetry_SendAll();

#ifdef __cplusplus
}
#endif

#endif  // SENSEHAT_INTERFACE_H
